### ISSUE TITLE
some keys not working

### ISSUE THREAD

**Issue by johnrees** [nwtgck/piping-ssh-web#1]
I managed to connect to a remote shell using https://piping-ssh.netlify.app (chrome browser on macOS 11.2.3, ubuntu 20.4 LTS remote server) but the following key presses aren't being registered

return
backspace
arrow keys

I'd love to get this working if possible, it's an amazing concept!

**Comment by nwtgck** [comment]
Thank you so much for the report!

Actually, it did work at least on macOS. In my environment this issue occurred. I fixed this issue with <https://github.com/nwtgck/piping-ssh-web/commit/04991a5f2b051bdf16202b697987dd9fd78703a5>.

I just changed "onkeydown" to "onkeyup". I don't know why "keydown" doesn't work now. I'm still trying investigation of the issue.
