### ISSUE TITLE
How to build code?

### ISSUE THREAD

**Issue by ParkerOu** [nwtgck/piping-ssh-web#225]
Because npm audit shows CVEs, I tried to upgrade package versions or switch packages, but found that the specified paths and folders couldn't be located.
repo: https://github.com/ParkerOu/piping-ssh-web

```
npm run serve
```

shows
```
can't find file to patch at input line 5
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/ssh/connection.go b/ssh/connection.go
|index 8f345ee..7d7204b 100644
|--- a/ssh/connection.go
|+++ b/ssh/connection.go
--------------------------
File to patch:
```

Apparently, there is no `ssh` subdirectory and `connection.go` file under `golang-crypto`.
How should the project be initialized?

**Comment by nwtgck** [comment]
Thanks for the issue. I'll upgrade pacakages.

>  How should the project be initialized?

This repository uses git submodules. You can use `git clone --recursive <this repo>` OR `cd <this repo> && git submodule update --init --recursive`

**Comment by nwtgck** [comment]
I updated:
* https://github.com/nwtgck/piping-ssh-web/commit/68d392d2d23e39ef2038554f99f0f9f7bab6b1b8
* https://github.com/nwtgck/piping-ssh-web/commit/bf93970e0aa753de07a56e710434723ff7057329

**Comment by ParkerOu** [comment]
After building the code, there are three files: `main.wasm`, `wasm_exec.js`, and `index.html`.
How could I set up piping-ssh-web?
I haven't used WebAssembly before and would like to try setting it up using pm2 + nginx.

**Comment by nwtgck** [comment]
You can find how to build in the CI:
* https://github.com/nwtgck/piping-ssh-web/blob/bf93970e0aa753de07a56e710434723ff7057329/.github/workflows/deploy.yml

You will get `./dist` after building.
