### ISSUE TITLE
Support for key based authentication 

### ISSUE THREAD

**Issue by dhananjaysathe** [nwtgck/piping-ssh-web#5]
Amazing work!

Out of curiosity I noticed https://github.com/nwtgck/ssh-keygen-web is it possible to use something like this or just copy private key and use it to authenticate against a remote server rather than username password

**Comment by nwtgck** [comment]
Thanks!

I also want key based authentication. This core SSH part of the project is highly based on [SSHy](https://github.com/stuicey/SSHy), and it has a similar issue too: https://github.com/stuicey/SSHy/issues/27. SSHy is currently inactive, so we may need to implement it. The future implementation may be here: https://github.com/nwtgck/piping-ssh-web/blob/f0fc180af375e35e86295be7c383875851d87f4e/src/auth_handler.js#L62.

**Comment by ParkerOu** [comment]
Any plan for implementation?

**Comment by ParkerOu** [comment]
Trying to use piping-ssh in project.
I have tried to use it, but I can't use it with my own server.
Have researched https://github.com/nwtgck/piping-server/issues/696 
Is it possible to use ssh client with bash or application based on piping-ssh?

Currently only key-based ssh is required. I will consider using key-based authentication in the future.
Thanks for the quick reply!

**Comment by nwtgck** [comment]
>  I have tried to use it, but I can't use it with my own server.

Do you want to self-host it? If not, Replit is best choice to have your own server.
Click fork button in https://replit.com/@nwtgck/piping to have the server.

>  Is it possible to use ssh client with bash or application based on piping-ssh?

Sorry, I'm no sure what you are going to do. Do you want to build a SSH client app running on browsers?

**Comment by ParkerOu** [comment]
> > I have tried to use it, but I can't use it with my own server.
> 
> Do you want to self-host it? If not, Replit is best choice to have your own server. Click the fork button in https://replit.com/@nwtgck/piping to have the server.

Yes, I want to self-host it.

> > Is it possible to use ssh client with bash or application based on piping-ssh?
> 
> Sorry, I'm no sure what you are going to do. Do you want to build a SSH client app running on browsers?

Sorry for my poor English.
I want to build a SSH client via website or PC, Linux applications.

**Comment by nwtgck** [comment]
@dhananjaysathe @ParkerOu

Now public key authentication supported!

I created this project from scratch with Go (`golang.org/x/crypto/ssh`) and WebAssembly. New version is already deployed:
<https://piping-ssh.nwtgck.org>
